// <auto-generated />
using System;
using ExamenP1_DRueda.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExamenP1_DRueda.Migrations
{
    [DbContext(typeof(ExamenP1_DRuedaContext))]
    partial class ExamenP1_DRuedaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DRueda", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("Fecha")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsMatriculado")
                        .IsRequired()
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SuCarreraIdCarrera")
                        .HasColumnType("integer");

                    b.Property<decimal?>("pagoMatricula")
                        .IsRequired()
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.HasIndex("SuCarreraIdCarrera");

                    b.ToTable("DRueda");
                });

            modelBuilder.Entity("ExamenP1_DRueda.Models.Carrera", b =>
                {
                    b.Property<int>("IdCarrera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCarrera"));

                    b.Property<string>("campus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("nombre_carrera")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("numero_semestres")
                        .HasColumnType("integer");

                    b.HasKey("IdCarrera");

                    b.ToTable("Carrera");
                });

            modelBuilder.Entity("DRueda", b =>
                {
                    b.HasOne("ExamenP1_DRueda.Models.Carrera", "SuCarrera")
                        .WithMany()
                        .HasForeignKey("SuCarreraIdCarrera")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SuCarrera");
                });
#pragma warning restore 612, 618
        }
    }
}
